# Generated by Django 3.1.6 on 2021-05-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210425_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name_client',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='number_client',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
